<a href="https://colab.research.google.com/github/Krish-nobita903/Movie-Review-Sentiment-Analysis-using-simple-RNN/blob/main/wordEmbedding_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
from tensorflow.keras.preprocessing.text import one_hot

In [68]:
sentences = [
    "The quick brown fox jumps over the dog.",
    "Python is a versatile programming language.",
    "Artificial intelligence is transforming industries.",
    "The sun sets in the west.",
    "She sells seashells by the seashore."
]

In [69]:
voc_size = 10000

In [70]:
one_hot_rep = [one_hot(words,voc_size) for words in sentences]

In [71]:
one_hot_rep

[[1332, 4188, 248, 2448, 4191, 279, 1332, 3876],
 [2330, 3921, 8163, 6810, 836, 2567],
 [8926, 5280, 3921, 979, 4678],
 [1332, 3495, 2486, 5628, 1332, 3692],
 [9682, 3535, 390, 8990, 1332, 9752]]

In [72]:
!pip install tensorflow

In [73]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [74]:
import numpy as np

In [75]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_rep,padding = 'pre',maxlen = sent_length)
print(embeded_docs)

[[1332 4188  248 2448 4191  279 1332 3876]
 [   0    0 2330 3921 8163 6810  836 2567]
 [   0    0    0 8926 5280 3921  979 4678]
 [   0    0 1332 3495 2486 5628 1332 3692]
 [   0    0 9682 3535  390 8990 1332 9752]]


In [76]:
## feature representation

dim = 10

In [81]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
#model.build(input_shape=(None, sent_length))  # Manually build the model
model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [82]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


array([[[ 0.00300242, -0.01956931,  0.04237283, -0.0029325 ,
         -0.02944497, -0.04098129, -0.01614708, -0.02284303,
          0.02589377,  0.04321666],
        [ 0.01033051, -0.00013513, -0.00963836, -0.03123161,
          0.00673051,  0.04708873, -0.02648361, -0.02923416,
         -0.03659592, -0.02891802],
        [-0.04847273,  0.0030748 ,  0.02880048,  0.02317352,
          0.03237641,  0.01306364, -0.03596463, -0.00598731,
         -0.04065974, -0.00768397],
        [-0.03314503, -0.00639069,  0.03606344,  0.0203898 ,
         -0.04531088,  0.01456866,  0.03493461,  0.02344744,
         -0.02893391, -0.02401271],
        [ 0.04394348,  0.00950034, -0.04437559, -0.04031382,
          0.01499471, -0.03192549,  0.0266291 , -0.02919455,
         -0.02966681, -0.0370387 ],
        [-0.00862248, -0.04367958, -0.04259543, -0.03398752,
          0.00562979,  0.00702836,  0.01424049, -0.00467734,
          0.0349118 ,  0.02837995],
        [ 0.00300242, -0.01956931,  0.04237283, -0.0

In [83]:
  embeded_docs[0]

array([1332, 4188,  248, 2448, 4191,  279, 1332, 3876], dtype=int32)

In [85]:
print(embeded_docs[0].shape)

(8,)


In [86]:
reshaped_input = embeded_docs[0].reshape(1, -1)

In [87]:
prediction = model.predict(reshaped_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step


In [88]:
prediction

array([[[ 0.00300242, -0.01956931,  0.04237283, -0.0029325 ,
         -0.02944497, -0.04098129, -0.01614708, -0.02284303,
          0.02589377,  0.04321666],
        [ 0.01033051, -0.00013513, -0.00963836, -0.03123161,
          0.00673051,  0.04708873, -0.02648361, -0.02923416,
         -0.03659592, -0.02891802],
        [-0.04847273,  0.0030748 ,  0.02880048,  0.02317352,
          0.03237641,  0.01306364, -0.03596463, -0.00598731,
         -0.04065974, -0.00768397],
        [-0.03314503, -0.00639069,  0.03606344,  0.0203898 ,
         -0.04531088,  0.01456866,  0.03493461,  0.02344744,
         -0.02893391, -0.02401271],
        [ 0.04394348,  0.00950034, -0.04437559, -0.04031382,
          0.01499471, -0.03192549,  0.0266291 , -0.02919455,
         -0.02966681, -0.0370387 ],
        [-0.00862248, -0.04367958, -0.04259543, -0.03398752,
          0.00562979,  0.00702836,  0.01424049, -0.00467734,
          0.0349118 ,  0.02837995],
        [ 0.00300242, -0.01956931,  0.04237283, -0.0